// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_4CMDzJz1ApCA_gsedGgV80bha88zjNk',
    appId: '1:677754514589:web:6c7fdb33523a4c34b97874',
    messagingSenderId: '677754514589',
    projectId: 'urbankitchen-71bd0',
    authDomain: 'urbankitchen-71bd0.firebaseapp.com',
    storageBucket: 'urbankitchen-71bd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBExzU6d7RaiWemCgenz_FSclLkw86ruH0',
    appId: '1:677754514589:android:6b3f624baeeedcabb97874',
    messagingSenderId: '677754514589',
    projectId: 'urbankitchen-71bd0',
    storageBucket: 'urbankitchen-71bd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHAAf79ESX7I7Bx00c4kRmc5sidlBiI1A',
    appId: '1:677754514589:ios:7ab78fed1b314c9eb97874',
    messagingSenderId: '677754514589',
    projectId: 'urbankitchen-71bd0',
    storageBucket: 'urbankitchen-71bd0.appspot.com',
    iosBundleId: 'com.example.kasirurban',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHAAf79ESX7I7Bx00c4kRmc5sidlBiI1A',
    appId: '1:677754514589:ios:21d2096bbc6b2ba2b97874',
    messagingSenderId: '677754514589',
    projectId: 'urbankitchen-71bd0',
    storageBucket: 'urbankitchen-71bd0.appspot.com',
    iosBundleId: 'com.example.kasirurban.RunnerTests',
  );
}
